### ISSUE TITLE
Command-line option parsing

### ISSUE THREAD

**Issue by mn200** [eatonphil/ponyo#15]
I don't know what your strategy is for picking up other random bits and bobs of SML that are distributed around the internet.  

Anyway, as a test case allowing you to explain that strategy: can I suggest you package the `GetOpt` code?  There's a known to be Poly/ML-compatible version of it [here](https://raw.githubusercontent.com/HOL-Theorem-Prover/HOL/master/tools/Holmake/GetOpt.sig) and [here](https://raw.githubusercontent.com/HOL-Theorem-Prover/HOL/master/tools/Holmake/GetOpt.sml).  (It's used in HOL, so I know it works with Poly/ML.) 

I don't even know if I had to do much if anything to it to make Poly/ML happy about it: it may well not differ from the SML/NJ sources at all.

**Comment by eatonphil** [comment]
Hey! I am sorry for the late response. And thank your for your time and interest! However, picking random bits and bobs of SML distributed around the internet is not really my strategy at all. Certainly there is a place for that. (I try to post everything I find on [/r/sml](https://www.reddit.com/r/sml), for example.)

My goal with Ponyo is primarily to control the quality of _interface_ more so than quality of code. Though I hope in time the quality of the interface will attract those who can help me work on quality of code.

To address your immediate question, there actually already has been a command-line parsing utility in Ponyo - modeled after the Python argparse module. While it needs work, it is already sufficient for use in the exported ponyo tools (ponyo, ponyo-make, ponyo-doc, etc.).
