### ISSUE TITLE
How are tests supposed to be written?

### ISSUE THREAD

**Issue by DanielRosenwasser** [eatonphil/ponyo#6]
As far as I see, tests are written with simple prints, but are there any specific verification steps that are taken that I'm not seeing?

**Comment by eatonphil** [comment]
Not yet. As you saw, those tests are useless for verification. That directory is simply a place I collected code checking that things worked at all. I would like to see a testing module (and perhaps a "test" extension to the ponyo tool) before thinking about unit tests. And this is definitely on the roadmap. Some places to look for inspiration will be OUnit (OCaml), HUnit (Haskell), and JUnit.

If you or someone else would like to get started on something like this, you're absolutely welcome to. Otherwise, I will begin working on this after I get some initial results with the doc-generator.

**Comment by tkob** [comment]
[SMLUnit](https://github.com/smlsharp/SMLUnit)?

But simple printf testing is not that bad, if it is equpped with an output verification tool. I created [rehearsal](https://github.com/tkob/rehearsal) command for that purpose and use it in my recent SML projects.

I don't know if you are going to like this approach, but a test script looks something like this:
https://github.com/tkob/rehearsal/blob/master/t/t/poly.t
and can be executed by `rehearsal -command poly -ps1 '> ' -ps2 '# ' /path/to/poly.t`
Maybe this would do for the time being (until ponyo's testing module is done?)

**Comment by DanielRosenwasser** [comment]
About running tests - correct me if I'm wrong, but right now, I have to manually call `main` after running `build.sml` in each directory, right?

**Comment by eatonphil** [comment]
Any standalone file needs to export a main function at the top level. It is good to encapsulate your main code logic in a Main structure. Take a look at the ponyo tool for some examples. The ponyo tool and not the "tests" in their current state reflect the best I've got on best practice.

**Comment by DanielRosenwasser** [comment]
Gotcha - thanks!

**Comment by eatonphil** [comment]
I guess I should note that this is somewhat unique to Poly/ML. Other implementations like SML/NJ and MLton in particular do not require this I think.

**Comment by DanielRosenwasser** [comment]
I don't believe they do; maybe @MatthewFluet could confirm.

**Comment by MatthewFluet** [comment]
Building standalone executables is one of the significant differences between SML systems.

I wrote up a little about some of the differences between SML/NJ and MLton for JonPRL/sml-red-jonprl#13.  Most of what I said about SML/NJ would also apply to Poly/ML; both will perform any top-level effects at "compile-time", while MLton will only perform top-level effects at "run-time".

Poly/ML's `polyc` tool expects a top-level `val main : unit -> unit` function that will be invoked when the resulting executable is run.  MLton would require an explicit `val _ = main ()` to invoke the function when the resulting executable is run.

**Comment by eatonphil** [comment]
There is an actual test suite now that is run using `make test`. Please check out the `test` directory for examples. I am have some preliminary work on automating the test runner but for now it's done manually.
